#!/usr/bin/env python3
"""Assess provider handshake probe TSV and emit a deterministic readiness summary."""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List

KEY_TAIL_RE = re.compile(r"key=\*\*\*([A-Za-z0-9_-]{3,})")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Assess provider handshake probe TSV")
    parser.add_argument(
        "--probe-tsv",
        required=True,
        help="Input probe TSV generated by scripts/provider_handshake_probe.py",
    )
    parser.add_argument(
        "--output-json",
        default="runtime_archives/bl100/tmp/provider_handshake_assessment.json",
        help="Output JSON summary path",
    )
    parser.add_argument(
        "--require-ready",
        action="store_true",
        help="Exit non-zero when assessment status is not ready",
    )
    return parser.parse_args()


def load_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"probe tsv not found: {path}")
    with path.open("r", encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        rows = list(reader)
    required = {"endpoint", "model", "probe", "http_code", "note"}
    if not rows:
        return []
    missing = sorted(required - set(rows[0].keys()))
    if missing:
        raise RuntimeError(f"probe tsv missing columns: {', '.join(missing)}")
    return rows


def extract_key_tails(rows: List[Dict[str, str]]) -> List[str]:
    tails: List[str] = []
    seen = set()
    for row in rows:
        note = row.get("note", "")
        match = KEY_TAIL_RE.search(note)
        if not match:
            continue
        tail = match.group(1)
        if tail in seen:
            continue
        seen.add(tail)
        tails.append(tail)
    return tails


def count_success(code_counter: Counter[str]) -> int:
    total = 0
    for code, count in code_counter.items():
        if code.isdigit() and 200 <= int(code) < 300:
            total += count
    return total


def decide_block_reason(code_counter: Counter[str], success_count: int) -> str:
    if success_count > 0:
        return "none"
    if not code_counter:
        return "empty_probe_matrix"
    codes = set(code_counter.keys())
    if codes <= {"401"}:
        return "invalid_api_key"
    if codes <= {"403"}:
        return "forbidden_or_gateway_policy"
    if codes <= {"000"}:
        return "transport_or_dns_failure"
    if "401" in codes and "403" in codes and codes <= {"401", "403"}:
        return "auth_or_access_policy_block"
    if "000" in codes:
        return "mixed_with_transport_failures"
    return "no_success_route"


def build_summary(rows: List[Dict[str, str]], probe_tsv: Path) -> Dict[str, Any]:
    code_counter = Counter((row.get("http_code", "") or "").strip() for row in rows)
    endpoint_counter = Counter((row.get("endpoint", "") or "").strip() for row in rows)
    success_count = count_success(code_counter)
    status = "ready" if success_count > 0 else "blocked"
    block_reason = decide_block_reason(code_counter, success_count)

    return {
        "probe_tsv": str(probe_tsv),
        "status": status,
        "block_reason": block_reason,
        "row_count": len(rows),
        "success_row_count": success_count,
        "http_code_counts": dict(sorted(code_counter.items())),
        "endpoint_counts": dict(sorted(endpoint_counter.items())),
        "key_tails": extract_key_tails(rows),
    }


def main() -> int:
    args = parse_args()
    probe_tsv = Path(args.probe_tsv)
    output_json = Path(args.output_json)
    output_json.parent.mkdir(parents=True, exist_ok=True)

    rows = load_rows(probe_tsv)
    summary = build_summary(rows, probe_tsv)

    output_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(output_json)

    if args.require_ready and summary["status"] != "ready":
        print(f"Probe assessment blocked: {summary['block_reason']}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
